services:
  gameserver:
    image: cat19/gameserver
    ports:
      - 8840:8840
    restart: always
    container_name: gameserver
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - mysql_mysqlnet
      - redis_redisnet
      - gamenet

networks:
  mysql_mysqlnet:
    external: true
  redis_redisnet:
    external: true
  gamenet:




